apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: build

resources:
  - secret/github-access-argo-event.yaml
  - secret/github-access-argo-workflow.yaml
  - argo-clusterrole.yaml 
  - secret/source-key-argo.yaml
  - secret/deploy-key-argo.yaml
  - secret/deploy-key-argocd.yaml
  - event-source.yaml
  - event-source-svc.yaml
  - event-sensor.yaml
  - workflow-template.yaml
  - repository.yaml 
  - application_spring-petclinic.yaml

  