apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workflows-rollout
  namespace: argocd
  annotations:
    # Improve performance by only syncing the paths that are needed https://argo-cd.readthedocs.io/en/latest/operator-manual/high_availability/#manifest-paths-annotation
    argocd.argoproj.io/manifest-generate-paths: .

  # Add this finalizer ONLY if you want these to cascade delete (A cascade delete, deletes both the app and its resources, rather than only the app.)
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  
spec:
  project: default

  syncPolicy:
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    automated:
      prune: true
      selfHeal: true

  sources:
    - repoURL: ${ARGOCD_ENV_GITHUB_REPO}/argo-deploy-applications-build.git
      targetRevision: main
      path: applications/overlays/local/workflows
      # Note: envsubst envs are injected through parent app via helm chart in tf.
      plugin:
        name: envsubst
        env:
          - name: ENV
            value: "${ARGOCD_ENV_ENV}"
          - name: DNS_ENV
            value: "${ARGOCD_ENV_DNS_ENV}"
          - name: DNS_DOMAIN
            value: "${ARGOCD_ENV_DNS_DOMAIN}"
          - name: GITHUB_ACCESS_ARGO
            value: ${GITHUB_ACCESS_ARGO}
          - name: GITHUB_ACCESS_ARGO_EVENTS
            value: ${GITHUB_ACCESS_ARGO_EVENTS}
          - name: DEPLOY_KEY_ARGOCD
            value: ${DEPLOY_KEY_ARGOCD}
          - name: DEPLOY_KEY_ARGO
            value: ${DEPLOY_KEY_ARGO}
          - name: SOURCE_KEY_ARGO
            value: ${SOURCE_KEY_ARGO}


  destination:
    server: https://kubernetes.default.svc
    namespace: build