apiVersion: v1
kind: Secret
metadata:
  name: github-access
  namespace: argo-events
type: Opaque
data:
  token: ${GITHUB_ACCESS_ARGO_EVENTS} #<access token>
  username: ${GITHUB_ACCESS_ARGO_EVENTS}  #<github username>
  password: ${GITHUB_ACCESS_ARGO_EVENTS}  #<github password>